version: '2'

services:

  rss2twitter:
    build: .
    image: umputun/rss2twitter:latest
    container_name: rss2twitter
    hostname: rss2twitter
    restart: always
    env_file: &env
      - .env

    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - "TEMPLATE={{.Title}}"

    # command: ["/srv/rss2twitter", "--dry"]
